# Generated by Django 4.0.4 on 2022-06-04 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_event_time_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(blank=True, default=datetime.time(4, 29, 21, 356690)),
        ),
    ]
